// Characters.js

window.personagemArcos = {
  "Touma": ["Index Arc", "Deep Blood Arc", "Sisters Arc (Index)", "Angel Falldown Arc",
    "Kazakiri Hyouka Arc", "Three Stories Arc", "Orsola Acquinas Rescue Arc",
    "Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)", "La Regina Del Mar Adriatico Ac",
    "Academic City Invasion Arc", "Skill Out Uprising Arc", "Battle Royale Arc",
    "Document of Constantine Arc", "Acqua of the back Arc", "Royal British Family Arc",
    "DRAGON Arc", "World War III Arc", "New Testament & Genesis Testment",
    "Level Upper Arc", "Sisters Arc (Railgun)", "Daihasei Festival Arc (Railgun)"],
  "Aogami": [],
  "Tsuchimikado": [],
  "Komoe": [],
  "Yomikawa": [],
  "Index": [],
  "Kaori": [],
  "Styl": [],
  "Himegami": [],
  "Izzard": ["Deep Blood Arc"],
  "Mikoto": [],
  "Kuroko": [],
  "Saten": [],
  "Uiharu": [],
  "Mii": [],
  "Harumi": [],
  "Miho": [],
  "Erii": [],
  "Telestina": [],
  "Mitsuko": [],
  "Maaya": [],
  "Wannai": [],
  "Mugino": [],
  "Frenda": [],
  "Riko": [],
  "Saiai": [],
  "Misaka10031": [],
  "Maika": [],
  "Accelerator": [],
  "Febrie": [],
  "Gabriel": [],
  "Ouma": [],
  "LastOrder": [],
  "Yoshikawa": [],
  "Hyouka": [],
  "Sherri": [],
  "Orsola": [],
  "Agnese": [],
  "Lucia": [],
  "Angeline": [],
  "Ringo": [],
  "Kakine": [],
  "Kaibi": [],
  "Yobou": [],
  "Souji": [],
  "Esther": [],
  "Huotou": [],
  "Iizumi": [],
  "Naruha": [],
  "Yakumaru": [],
  "Seike": [],
  "Hirumi": [],
  "Hishigata": [],
  "Himegi": [],
  "Yumi": [],
  "Mami": [],
  "Musujime": [],
  "Fukiyose": [],
  "Oriana": [],
  "Lidvia": [],
  "Yoshio": [],
  "Misaki": [],
  "Junko": [],
  "Mitori": [],
  "Dolly": [],
  "Gensei": [],
  "Sogiita": [],
  "Itsuwa": [],
  "Biagio": [],
  "Vento": [],
  "Amata": [],
  "Rakko": [],
  "Iruka": [],
  "Kuriba": [],
  "Doppelganger": [],
  "Hamazura": [],
  "Ritoku": [],
  "Hanzou": [],
  "Professor": [],
  "Sunazara": [],
  "Xochtl": [],
  "Terra": [],
  "Acqua": [],
  "Elizard": [],
  "Villian": [],
  "Rimea": [],
  "Carissa": [],
  "KnightLeader": [],
  "Beiloupe": [],
  "Floris": [],
  "Lessar": [],
  "Lancis": [],
  "Flamma": ["Acqua of the back Arc", "Royal British Family Arc", "World War III Arc"],
  "Aiwass": [],
  "Sasha": [],
  "Fremea": []
};

const personagens = Object.keys(window.personagemArcos);
window.personagemGeneros = {
  "Touma": "masculino",
  "Aogami": "masculino",
  "Index": "feminino",
  "Mikoto": "feminino",
  "Kuroko": "feminino",
  "Accelerator": "masculino",
  "Misaki": "feminino",
  "Frenda": "feminino",
  "Mugino": "feminino",
  "Last Order": "feminino",
  "Kaori": "feminino",
  "Styl": "masculino",
  "Himegami": "feminino",
  "Izzard": "masculino",
  "Mikoto": "feminino",
  "Kuroko": "feminino",
  "Saten": "feminino",
  "Uiharu": "feminino",
  "Mii": "feminino",
  "Harumi": "feminino",
  "Miho": "feminino",
  "Erii": "feminino",
  "Telestina": "feminino",
  "Mitsuko": "feminino",
  "Maaya": "feminino",
  "Wannai": "feminino",
  "Mugino": "feminino",
  "Frenda": "feminino",
  "Riko": "feminino",
  "Saiai": "feminino",
  "Maika": "feminino",
  "Misaka10031": "feminino",
  "Accelerator": "masculino",
  "Febrie": "feminino",
  "Ouma": "masculino",
  "LastOrder": "feminino",
  "Yoshikawa": "feminino",
  "Hyouka": "feminino",
  "Sherri": "feminino",
  "Orsola": "feminino",
  "Agnese": "feminino",
  "Lucia": "feminino",
  "Angeline": "feminino",
  "Ringo": "feminino",
  "Kakine": "masculino",
  "Kaibi": "feminino",
  "Yobou": "masculino",
  "Souji": "masculino",
  "Esther": "feminino",
  "Huotou": "feminino",
  "Iizumi": "feminino",
  "Naruha": "feminino",
  "Yakumaru": "feminino",
  "Seike": "masculino",
  "Hirumi": "feminino",
  "Hishigata": "masculino",
  "Himegi": "feminino",
  "Yumi": "feminino",
  "Mami": "feminino",
  "Musujime": "feminino",
  "Fukiyose": "feminino",
  "Oriana": "feminino",
  "Lidvia": "feminino",
  "Yoshio": "masculino",
  "Misaki": "feminino",
  "Junko": "feminino",
  "Mitori": "feminino",
  "Dolly": "feminino",
  "Gensei": "masculino",
  "Sogiita": "masculino",
  "Itsuwa": "feminino",
  "Biagio": "masculino",
  "Vento": "feminino",
  "Amata": "masculino",
  "Rakko": "feminino",
  "Iruka": "feminino",
  "Kuriba": "feminino",
  "Doppelganger": "feminino",
  "Hamazura": "masculino",
  "Ritoku": "masculino",
  "Hanzou": "masculino",
  "Professor": "masculino",
  "Sunazara": "masculino",
  "Xochtl": "feminino",
  "Terra": "masculino",
  "Acqua": "masculino",
  "Flamma": "masculino",
  "Elizard": "feminino",
  "Villian": "feminino",
  "Rimea": "feminino",
  "Carissa": "feminino",
  "KnightLeader": "masculino",
  "Beiloupe": "feminino",
  "Floris": "feminino",
  "Lessar": "feminino",
  "Lancis": "feminino",
  "Sasha": "feminino",
  "Fremea": "feminino"
};

const arcList = [
  "Index Arc", "Deep Blood Arc", "Sisters Arc (Index)", "Angel Falldown Arc",
  "Kazakiri Hyouka Arc", "Three Stories Arc", "Orsola Acquinas Rescue Arc",
  "Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)", "La Regina Del Mar Adriatico Ac",
  "Academic City Invasion Arc", "Skill Out Uprising Arc", "Battle Royale Arc",
  "Document of Constantine Arc", "Acqua of the back Arc", "Royal British Family Arc",
  "DRAGON Arc", "World War III Arc", "New Testament & Genesis Testment",
  "Level Upper Arc", "Big Spider Arc", "Poltergeist Arc", "Sisters Arc (Railgun)",
  "Silent Party Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc",
  "Jailbreaker Arc", "First Year Arc", "Necromancer Arc", "Nectar Arc",
  "Enemy ITEM Arc", "Honey Bee Queen Arc", "Dark Justice Arc",
  "Yuzuriha Ringo Arc", "Astral Buddy Arc", "Tokiwadai Election Arc"
];

window.personagens = personagens;
window.arcList = arcList;
