// Characters.js

window.personagemArcos = {
  "Mikagami": ["First Year Arc"],
  "Kazanin": ["First Year Arc"],
  "Aika": ["First Year Arc"],
  "Asakura": ["First Year Arc"],
  "Rina": ["First Year Arc"],
  "Sena": ["First Year Arc"],
  "Sha": ["First Year Arc"],
  "Ouyang": ["First Year Arc"],
  "Lin": ["First Year Arc"],
  "Lily": ["First Year Arc"],
  "Reiri": ["First Year Arc"],
  "Kiyoshi": ["First Year Arc"],
  "Suika": ["First Year Arc"],
  "Enjou": ["First Year Arc"],
  "Rurikaesu": ["First Year Arc"],
  "Touma": ["Index Arc", "Deep Blood Arc", "Sisters Arc (Index)", "Angel Falldown Arc",
    "Kazakiri Hyouka Arc", "Three Stories Arc", "Orsola Acquinas Rescue Arc",
    "Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)", "La Regina Del Mar Adriatico Arc",
    "Academic City Invasion Arc", "Skill Out Uprising Arc", "Battle Royale Arc",
    "Document of Constantine Arc", "Acqua of the back Arc", "Royal British Family Arc",
    "DRAGON Arc", "World War III Arc", "New Testament & Genesis Testment",
    "Level Upper Arc", "Sisters Arc (Railgun)", "Daihasei Festival Arc (Railgun)"],
  "Aogami": ["Index Arc", "Deep Blood Arc", "Sisters Arc (Index)", "Angel Falldown Arc",
    "Three Stories Arc", "Kazakiri Hyouka Arc", "Daihasei Festival Arc (Index)",
    "Academic City Invasion Arc", "Skill Out Uprising Arc", "Document of Constantine Arc",
    "Acqua of the back Arc", "Royal British Family Arc", "Silent Party Arc", "Dream Ranker Arc"],
  "Tsuchimikado": ["Index Arc", "Deep Blood Arc", "Angel Falldown Arc", "Three Stories Arc",
    "Kazakiri Hyouka Arc", "Orsola Acquinas Rescue Arc", "Daihasei Festival (Index)",
    "La regina del mar adriatico Arc", "Academic City Arc", "Skill Out Uprising",
    "Document of Constantine Arc", "Battle Royale Arc", "Acqua of the back Arc", "British Royal Family Arc",
    "DRAGON Arc", "Dream Ranker Arc"],
  "Komoe": ["Index Arc", "Sisters Arc (Index)", "Angel Falldown Arc", "Daihasei Festival Arc (Index)",
    "Academic City Invasion Arc", "Skill Out Uprising Arc", "Document of Constantine Arc", "Acqua of the back Arc",
    "British Royal Family Arc", "DRAGON Arc", "Level Upper Arc", "Poltergeist Arc", "Silent Party Arc",
    "Daihasei Festival (Railgun)", "Dream Ranker Arc"],
  "Yomikawa": ["Kazakiri Hyouka Arc", "Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)",
    "Academic City Invasion Arc", "Skill Out Uprising", "Document of Constantine Arc", "Battle Royale Arc",
    "Acqua of the Back Arc", "British Royal Family Arc", "DRAGON Arc", "Level Upper Arc", "Poltergeist Arc",
    "Silent Party Arc", "Dream Ranker Arc", "Necromancer Arc", "Nectar Arc"],
  "Index": ["Index Arc", "Deep Blood Arc", "Sisters Arc (Index)", "Angel Falldown Arc",
    "Kazakiri Hyouka Arc", "Three Stories Arc", "Orsola Acquinas Rescue Arc",
    "Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)", "La Regina Del Mar Adriatico Arc",
    "Academic City Invasion Arc", "Skill Out Uprising Arc", "Battle Royale Arc",
    "Document of Constantine Arc", "Acqua of the back Arc", "Royal British Family Arc",
    "DRAGON Arc", "World War III Arc", "New Testament & Genesis Testment",
    "Sisters Arc (Railgun)", "Dream Ranker Arc"],
  "Kaori": ["Index Arc", "Angel Falldown Arc", "Orsola Acquinas Rescue Arc", "Daihasei Festival Arc (Index)",
    "La Regina del Mar Adriatico Arc", "Academic City Invasion Arc",
    "Anglican Church Russian Orthodox Church Pre war Conference", "Acqua of the back Arc", "British Royal Family Arc",
    "World War III Arc"],
  "Styl": ["Index Arc", "Deep Blood Arc", "Orsola Acquinas Rescue Arc", "Daihasei Festival Arc", "Academic City Invasion Arc",
    "Document of Constantine Arc", "Acqua of the back Arc", "British Royal Family Arc", "World War III Arc"],
  "Nakimoto": ["Necromancer Arc", "Nectar Arc", "Tree Diagram Remnant Arc", "Honey Bee Queen Arc"],
  "Secretary": ["Necromancer Arc", "Nectar Arc"],
  "Himegami": ["Deep Blood Arc", "Sisters Arc (Index)", "Angel Falldown Arc", "Three Stories Arc", "Kazakiri Hyouka Arc",
    "Daihasei Festival Arc(Index)", "Academic City Invasion Arc", "Skill Out Uprising Arc", "Acqua of the back Arc",
    "British Royal Family Arc"],
  "Izzard": ["Deep Blood Arc"],
  "Mikoto": ["Index Arc", "Sisters Arc (Index)",
    "Kazakiri Hyouka Arc", "Three Stories Arc", "Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)",
    "La Regina Del Mar Adriatico Arc", "Academic City Invasion Arc", "Skill Out Uprising Arc", "Document of Constantine Arc",
    "Acqua of the back Arc", "Royal British Family Arc", "World War III Arc", "New Testament & Genesis Testment", "Level Upper Arc",
    "Big Spider Arc", "Poltergeist Arc", "Sisters Arc (Railgun)", "Silent Party Arc", "Daihasei Festival Arc (Railgun)",
    "Dream Ranker Arc", "Jailbreaker Arc", "First Year Arc"],
  "Kuroko": ["Index Arc", "Sisters Arc (Index)", "Kazakiri Hyouka Arc", "Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)",
    "Academic City Invasion Arc", "Document of Constantine Arc", "World War III Arc", "Level Upper Arc", "Big Spider Arc", "Poltergeist Arc",
    "Sisters Arc (Railgun)", "Silent Party Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc", "Astral Buddy Arc",
    "Tokiwadai Election Arc"],
  "Saten": ["Battle Royale Arc", "Level Upper Arc", "Big Spider Arc", "Poltergeist Arc", "Sisters Arc (Index)", "Silent Party Arc",
    "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc", "Astral Buddy Arc"],
  "Uiharu": ["Tree Diagram Remnant Arc", "Daihasei Festival Arc", "Academic City Invasion Arc", "Document of Constantine Arc", "Battle Royale Arc",
    "Level Upper Arc", "Big Spider Arc", "Poltergeist Arc", "Sisters Arc (Railgun)", "Silent Party Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc",
    "Jailbreaker Arc", "Astral Buddy Arc"],
  "Harumi": ["Level Upper Arc", "Poltergeist Arc"],
  "Mii": ["Level Upper Arc", "Big Spider Arc", "Poltergeist Arc", "Sisters Arc (Railgun)", "Silent Party Arc", "Daihasei Festival Arc (Index)", "Dark Justice Arc"],
  "Wataru": ["Big Spider Arc"],
  "Hebitani": ["Big Spider Arc"],
  "Tamezo": ["Big Spider Arc"],
  "Miho": ["Level Upper Arc", "Poltergeist Arc"],
  "Erii": ["Poltergeist Arc", "Sisters Arc (Railgun)", "Silent Party Arc", "Freshmen Arc"],
  "Telestina": ["Level Upper Arc", "Poltergeist Arc", "Silent Party Arc", "World War III Arc", "Baggage City Arc", "New Year's Arc"],
  "Mitsuko": ["Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)", "Element Arc", "Kamisato Rescue Arc", "New Year's Arc", "Level Upper Arc", "Poltergeist Arc",
    "Silent Party Arc", "Three Stories Arc", "Dream Ranker Arc", "Jailbreaker Arc"],
  "Maaya": ["Three Stories Arc", "Element Arc", "Level Upper Arc", "Poltergeist Arc", "Silent Party Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc"],
  "Wannai": ["Three Stories Arc", "Element Arc", "Level Upper Arc", "Poltergeist Arc", "Silent Party Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc"],
  "Mugino": ["Battle Royale Arc", "DRAGON Arc", "World War III Arc", "Freshmen Arc", "Homecoming Arc", "Ichinaran Festival Arc", "Agitate Halation Arc", "Magic God Othinus Arc",
    "St. Germain Arc", "Processor Suit Arc", "Coronzon Arc", "Kamijou Arc", "Operation Handcuffs Arc", "New Year's Arc", "Level Upper Arc", "Sisters Arc (Railgun)", "Silent Party Arc",
    "Daihasei Festival Arc (Railgun)", "Enemy ITEM Arc", "Honey Bee Queen Arc", "Dark Justice Arc", "Mugino Family Arc"],
  "Frenda": ["Battle Royale Arc", "Level Upper Arc", "Sisters Arc (Railgun)", "Silent Party Arc", "Daihasei Festival Arc (Railgun)", "Enemy ITEM Arc", "Honey Bee Queen Arc", "Dark Justice Arc",
    "Mugino Family Arc"],
  "Riko": ["Battle Royale Arc", "DRAGON Arc", "World War III Arc", "Freshmen Arc", "Homecoming Arc", "Ichinaran Festival Arc", "Agitate Halation Arc", "Magic God Othinus Arc", "St. Germain Arc",
    "Salome Arc", "Processor Suit Arc", "Coronzon Arc", "Kamijou Arc", "Operation Handcuffs Arc", "Post-Handcuffs Arc", "New Year's Arc", "Ressurection Arc", "Level Upper Arc", "Sisters Arc (Railgun)",
    "Silent Party Arc", "Daihasei Festival Arc (Railgun)", "Enemy ITEM Arc", "Honey Bee Queen Arc", "Dark Justice Arc", "Mugino Family Arc"],
  "Saiai": ["Battle Royale Arc", "DRAGON Arc", "World War III Arc", "Freshmen Arc", "Homecoming Arc", "Ichinaran Festival Arc", "Agitate Halation Arc", "Magic God Othinus Arc",
    "St. Germain Arc", "Processor Suit Arc", "Coronzon Arc", "Kamijou Arc", "Operation Handcuffs Arc", "New Year's Arc", "Level Upper Arc", "Sisters Arc (Railgun)", "Silent Party Arc",
    "Daihasei Festival Arc (Railgun)", "Enemy ITEM Arc", "Honey Bee Queen Arc", "Dark Justice Arc", "Mugino Family Arc"],
  "Hanano": ["Battle Royale Arc", "DRAGON Arc", "World War III Arc", "Sisters Arc (Railgun)", "Daihasei Festival Arc (Railgun)", "Enemy ITEM Arc", "Honey Bee Queen Arc", "Dark Justice Arc", "Mugino Family Arc"],
  "Misaka10031": [],
  "Maika": ["Sisters Arc (Index)", "Three Stories Arc", "Kazakiri Hyouka Arc", "Orsola Acquinas Rescue Arc", "Daihasei Festival Arc (Index)", "Academic City Invasion Arc", "Acqua of the back Arc", "DRAGON Arc",
    "Homecoming Arc", "Ichinaran Festival Arc", "Agitate Halation Arc", "Aleister Crowley Arc", "Processor Suit Arc", "Kamijou Arc", "Dream Ranker Arc"],
  "Shinobu": ["Sisters Arc (Railgun)", "Silent Party Arc"],
  "Accelerator": ["Sisters Arc (Index)", "Three Stories Arc", "Kazakiri Hyouka Arc", "Tree Diagram Remanant Arc", "Academic City Invasion Arc", "Document of Constantine Arc", "Battle Royale Arc", "DRAGON Arc",
    "World War III Arc", "Freshmen Arc", "Homecoming Arc", "Hawaii Invasion Arc", "Baggage City Arc", "Ichinaran Festival Arc", "Agitate Halation Arc", "Magic God Othinus Arc", "Salome Arc", "Aleister Crowley Arc",
    "Processor Suit Arc", "Coronzon Arc", "Kamijou Arc", "Christmas Eve Arc", "Christmas Day Arc", "Operation Handcuffs Arc", "Los Angeles Arc", "Post-Handcuffs Arc", "New Year's Arc", "Ressurection Arc", "Sisters Arc (Railgun)",
    "Silent Party Arc", "Daihasei Festival (Railgun)", "Necromancer Arc", "Nectar Arc"],
  "Febrie": ["Silent Party Arc"],
  "Janie": ["Silent Party Arc"],
  "Haruki": ["Silent Party Arc"],
  "Kosako": ["Silent Party Arc"],
  "Hirotada": ["Silent Party Arc"],
  "Kenji": ["Silent Party Arc"],
  "Sakurai": ["Silent Party Arc"],
  "Gabriel": ["Angel Falldown Arc", "World War III Arc", "Coronzon Arc"],
  "Shiratori": ["Dark Justice Arc"],
  "Mitsuki": ["Three Stories Arc"],
  "Unabara": ["Three Stories Arc", "Astral Buddy Arc", "Tokiwadai Election Arc"],
  "Ouma": ["Three Stories Arc", "Kazakiri Hyouka Arc", "Ichinaran Festival Arc"],
  "LastOrder": ["Three Stories Arc", "Kazakiri Hyouka Arc", "Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)", "Academic City Invasion Arc", "Skill Out Uprising", "Battle Royale Arc", "DRAGON Arc", "World War III Arc",
    "Freshmen Arc", "Homecoming Arc", "Ichinaran Festival Arc", "Magic God Othinus Arc", "Coronzon Arc", "Kamijou Arc", "Christmas Eve Arc", "New Year's Arc", "Sisters Arc (Railgun)", "Silent Party Arc", "Daihasei Festival Arc (Railgun)",
    "Necromancer Arc", "Nectar Arc"],
  "Yoshikawa": ["Three Stories Arc", "Tree Diagram Remnant Arc", "Academic City Invasion Arc", "Skill-Out Uprising Arc", "DRAGON Arc", "Homecoming Arc", "Ichinaran Festival Arc", "Magic God Othinus Arc", "Magic God Invasion Arc", "Coronzon Arc",
    "Kamijou Arc", "New Year's Arc", "Dream Ranker Arc", "Necromancer Arc"],
  "Hyouka": ["Kazakiri Hyouka Arc", "Academic City Invasion Arc", "British Royal Family Arc", "World War III Arc", "Homecoming Arc", "Post-Handcuffs Arc", "New Year's Arc"],
  "Sherry": ["Kazakiri Hyouka Arc", "Orsola Acquinas Rescue Arc", "Daihasei Festival Arc (Index)", "Anglican Church Russian Orthodox Church Pre war Conference", "Acqua of the Back Arc", "British Royal Family Arc", "Homecoming Arc", "Magic God Othinus Arc"],
  "Orsola": ["Orsola Acquinas Rescue Arc", "La Regina del Mar Adriatico Arc", "Acqua of the Back Arc", "British Royal Family Arc", "World War III Arc", "Homecoming Arc", "Magic God Othinus Arc", "Coronzon Arc", "Kamijou Arc"],
  "Agnese": ["Orsola Acquinas Rescue Arc", "La Regina del Mar Adriatico Arc", "Academic City Invasion Arc", "Anglican Church Russian Orthodox Church Pre war Conference", "Document of Constantine Arc", "British Royal Family Arc", "World War III Arc",
    "Homecoming Arc", "Magic God Othinus Arc", "Coronzon Arc", "New Year's Arc"],
  "Lucia": ["Orsola Acquinas Rescue Arc", "La Regina del Mar Adriatico Arc", "Academic City Invasion Arc", "Anglican Church Russian Orthodox Church Pre war Conference", "Document of Constantine Arc", "British Royal Family Arc", "World War III Arc",
    "Homecoming Arc", "Magic God Othinus Arc", "Coronzon Arc", "New Year's Arc"],
  "Angeline": ["Orsola Acquinas Rescue Arc", "La Regina del Mar Adriatico Arc", "Academic City Invasion Arc", "Anglican Church Russian Orthodox Church Pre war Conference", "Document of Constantine Arc", "British Royal Family Arc", "World War III Arc",
    "Homecoming Arc", "Magic God Othinus Arc", "Coronzon Arc", "New Year's Arc"],
  "Ringo": ["Yuzuriha Ringo Arc"],
  "Kakine": ["Sister's Arc (Index)", "Battle Royale Arc", "DRAGON Arc", "World War III Arc", "Baggage City Arc", "Ichinaran Festival Arc", "Magic God Othinus Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Yuzuriha Ringo Arc"],
  "Kaibi": ["Battle Royale Arc", "DRAGON Arc", "Operation Handcuffs Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Yuzuriha Ringo Arc", "Mugino Family Arc"],
  "Yobou": ["Battle Royale Arc", "Dream Ranker Arc", "Yuzuriha Ringo Arc"],
  "Souji": ["Yuzuriha Ringo Arc"],
  "Esther": ["Necromancer Arc"],
  "Huotou": ["Necromancer Arc"],
  "Iizumi": ["Necromancer Arc", "Dream Ranker Arc", "Jailbreaker Arc"],
  "Naruha": ["Necromancer Arc", "Dream Ranker Arc", "Jailbreaker Arc"],
  "Yakumaru": ["Necromancer Arc", "Dream Ranker Arc", "Jailbreaker Arc"],
  "Seike": ["Necromancer Arc", "Dream Ranker Arc", "Jailbreaker Arc"],
  "Hirumi": ["Necromancer Arc"],
  "Hishigata": ["Necromancer Arc"],
  "Himegi": ["Nectar Arc"],
  "Yumi": ["Nectar Arc"],
  "Mami": ["Nectar Arc"],
  "Chef": ["Nectar Arc"],
  "Tao": ["Nectar Arc"],
  "Musujime": ["Kazakiri Hyouka Arc", "Tree Diagram Remnant Arc", "Skill Out Uprising", "Battle Royale Arc", "DRAGON Arc", "Homecoming Arc", "Operation Handcuffs Arc", "Dream Ranker Arc"],
  "Fukiyose": ["Daihasei Festival Arc (Index)", "Skill Out Uprising", "Acqua of the Back Arc", "British Royal Family Arc", "Homecoming Arc", "Ichinaran Festival Arc", "Magic God Othinus Arc", "Magic God Invasion Arc", "Salome Arc", "Element Arc", "Kamisato Rescue Arc",
    "Christmas Day Arc", "Los Angeles Arc", "Post-Handcuffs Arc", "New Year's Arc", "Ressurection Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc"],
  "Oriana": ["Daihasei Festival Arc (Index)", "Document of Constantine Arc", "British Royal Family Arc", "Magic God Othinus Arc", "Coronzon Arc"],
  "Lidvia": ["Daihasei Festival Arc (Index)", "Document of Constantine Arc", "Magic God Othinus Arc"],
  "Professor": ["Battle Royale Arc", "Daihasei Festival Arc (Railgun)"],
  "Yoshio": ["Battle Royale Arc", "Daihasei Festival Arc (Railgun)"],
  "Xochtl": ["Battle Royale Arc", "DRAGON Arc", "Homecoming Arc", "Magic God Othinus Arc", "Operation Handcuffs Arc", "Daihasei Festival Arc (Railgun)"],
  "Saraku": ["Battle Royale Arc", "Daihasei Festival Arc (Railgun)"],
  "Misaki": ["Sisters Arc (Index)", "Sisters Arc (Railgun)", "Silent Party Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc", "First Year Arc", "Astral Buddy", "Tokiwadai Election Arc"],
  "Junko": ["Sisters Arc (Railgun)", "Silent Party Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc", "First Year Arc", "Astral Buddy", "Tokiwadai Election Arc"],
  "Mitori": ["Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc", "Tokiwadai Election Arc", "Kamijou Arc", "Los Angeles Arc"],
  "Dolly": ["Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc", "Tokiwadai Election Arc", "Kamijou Arc", "Los Angeles Arc"],
  "Megumi": ["Daihasei Festival Arc (Railgun)", "Dream Ranker Arc"],
  "Satori": ["New Year's Arc", "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Astral Buddy Arc", "Tokiwadai Election Arc"],
  "Mei": ["Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc", "Astral Buddy Arc", "Tokiwadai Election Arc"],
  "Kii": ["Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc", "Astral Buddy Arc", "Tokiwadai Election Arc"],
  "Kisa": ["Daihasei Festival Arc (Railgun)", "Astral Buddy Arc", "Tokiwadai Election Arc", "First Year Arc"],
  "Kazan": ["Daihasei Festival Arc (Railgun)", "Astral Buddy Arc", "First Year Arc"],
  "Wakana": ["Tokiwadai Election Arc"],
  "Fuigo": ["Daihasei Festival Arc (Railgun)", "Astral Buddy Arc", "First Year Arc"],
  "Gensei": ["Level Upper Arc", "Poltergeist Arc", "Silent Party Arc", "Daihasei Festival Arc"],
  "Sogiita": ["Agitate Halation Arc", "Magic God Othinus Arc", "Level Upper Arc", "Daihasei Festival Arc (Railgun)", "Astral Buddy Arc"],
  "Itsuwa": ["Orsola Acquinas Rescue Arc", "La Regina Del Mar Adriatico", "Anglican Church Russian Orthodox Church Pre war Conference", "Document of Constantine Arc", "Acqua of the Back Arc", "World War III Arc", "Homecoming Arc", "Coronzon Arc", "Kamijou Arc",
    "Ressurection Arc"],
  "Biagio": ["La Regina del Mar Adriatico", "Document of Constantine Arc"],
  "Vento": ["La Regina del Mar Adriatico", "Academic City Invasion Arc", "Acqua of the Back Arc", "British Royal Family Arc", "World War III Arc, Magic God Othinus Arc"],
  "Terra": ["Academic City Arc", "Document of Constantine Arc", "Acqua of the Back Arc", "World War III Arc", "Ichinaran Festival Arc", "Magic God Othinus Arc"],
  "Acqua": ["Academic City Invasion Arc", "Acqua of the Back Arc", "British Royal Family Arc", "World War III Arc", "Magic God Othinus Arc", "Coronzon Arc", "Kamijou Arc"],
  "Flamma": ["Acqua of the back Arc", "Royal British Family Arc", "World War III Arc"],
  "Amata": ["Academic City Invasion Arc"],
  "Thomas": ["Academic City Invasion Arc", "DRAGON Arc"],
  "Rakko": ["Dream Ranker Arc", "Battle Royale Arc"],
  "Iruka": ["Astral Buddy"],
  "Makigami": ["Astral Buddy"],
  "Kuriba": ["Dream Ranker Arc"],
  "Doppelganger": ["Dream Ranker Arc"],
  "Ayame": ["Agitate Halation Arc", "Christmas Day Arc", "Dream Ranker Arc", "Jailbreaker Arc"],
  "Shuri": ["Baggage City Arc", "Magic God Othinus Arc", "Jailbreaker Arc"],
  "Asai": ["Baggage City Arc", "Jailbreaker Arc"],
  "Sakata": ["Baggage City Arc", "Jailbreaker Arc"],
  "Yasu": ["Baggage City Arc", "Jailbreaker Arc"],
  "Shoubu": ["Jailbreaker Arc"],
  "Tsurigane": ["Jailbreaker Arc"],
  "Raifu": ["Jailbreaker Arc"],
  "Suzuran": ["Jailbreaker Arc"],
  "Kimi": ["Jailbreaker Arc"],
  "Honoka": ["Jailbreaker Arc"],
  "Kuruwa": ["Freshmen Arc", "Magic God Othinus Arc", "Processor Suit Arc", "Post Handcuffs Arc", "Jailbreaker Arc"],
  "Hamazura": ["Skill Out Uprising", "Battle Royale Arc", "DRAGON Arc", "World War III Arc", "Freshmen Arc", "Homecoming Arc", "Hawaii Invasion Arc", "Ichinaran Festival Arc", "Agitate Halation Arc", "Magic God Othinus Arc", "St. Germain Arc", "Magic God Invasion Arc",
    "Salome Arc", "Element Arc", "Aleister Crowley Arc", "Processor Suit Arc", "Coronzon Arc", "Kamijou Arc", "Christmas Day Arc", "Operation Handcuffs Arc", "Los Angeles Arc", "Post-Handcuffs Arc", "New Year's Arc", "Ressurection Arc"],
  "Ritoku": ["Skill Out Uprising", "Freshmen Arc", "Magic God Othinus"],
  "Hanzou": ["Skill Out Uprising", "Freshmen Arc", "Magic God Othinus", "Magic GOd Invasion Arc", "Processor Suit Arc", "Operation Handcuffs Arc"],
  "Sunazara": ["Battle Royale Arc", "DRAGON Arc", "Agitate Halation Arc"],
  "Monaka": ["Document of Constantine Arc", "Battle Royale Arc", "DRAGON Arc", "Kamijou Arc"],
  "Elizard": ["British Royal Family Arc", "Magic God Othinus Arc", "Coronzon Arc", "Kamijou Arc"],
  "Villian": ["British Royal Family Arc", "Coronzon Arc", "Kamijou Arc"],
  "Rimea": ["British Royal Family Arc", "Coronzon Arc", "Kamijou Arc"],
  "Carissa": ["British Royal Family Arc", "World War III Arc", "Magic God Othinus Arc", "Coronzon Arc", "Kamijou Arc"],
  "KnightLeader": ["Anglican Church Russian Orthodox Church Pre war Conference", "British Royal Family Arc", "World War III Arc", "Magic God Othinus Arc", "Coronzon Arc", "Kamijou Arc"],
  "Beiloupe": ["British Royal Family Arc"],
  "Floris": ["British Royal Family Arc", "World War III Arc", "Magic God Othinus"],
  "Lessar": ["British Royal Family Arc", "World War III Arc", "Magic God Othinus", "Coronzon Arc", "Christmas Day Arc"],
  "Lancis": ["British Royal Family Arc", "Homecoming Arc"],
  "Shiokishi": ["DRAGON Arc", "Kamijou Arc"],
  "Stephanie": ["DRAGON Arc", "Agitate Halation Arc", "St. Germain Arc"],
  "Aiwass": ["Orsola Acquinas Rescue Arc", "Battle Royale Arc", "DRAGON Arc", "World War III Arc", "Magic God Othinus Arc", "Mental Out Arc", "Aleister Crowley Arc", "Processor Suit Arc", "Coronzon Arc", "Kamijou Arc", "Christmas Day Arc",
    "Operation Handcuffs Arc", "New Year's Arc"],
  "Elizalina": ["World War III Arc"],
  "Sasha": ["Angel Falldown Arc", "Academic City Invasion Arc", "Anglican Church Russian Orthodox Church Pre war Conference", "British Royal Family Arc", "World War III Arc", "Magic God Othinus Arc"],
  "Fremea": ["Skill Out Uprising", "Freshmen Arc", "Homecoming Arc", "Ichinaran Festival Arc", "Agitate Halation Arc", "Magic God Othinus Arc", "Magic God Invasion Arc", "Element Arc", "Christmas Eve Arc", "Christmas Day Arc", "Operation Handcuffs Arc",
    "Enemy ITEM Arc", "Honey Bee Queen Arc", "Dark Justice Arc", "Mugino Family Arc"],
  "Hisato": ["Agitate Halation Arc"],
};

const personagens = Object.keys(window.personagemArcos);
window.personagemGeneros = {
  "Mikagami": "feminino",
  "Kazanin": "feminino",
  "Aika": "feminino",
  "Asakura": "feminino",
  "Rina": "feminino",
  "Sena": "feminino",
  "Sha": "feminino",
  "Ouyang": "feminino",
  "Lin": "feminino",
  "Lily": "feminino",
  "Reiri": "feminino",
  "Kiyoshi": "feminino",
  "Suika": "feminino",
  "Enjou": "feminino",
  "Rurikaesu": "feminino",
  "Touma": "masculino",
  "Aogami": "masculino",
  "Tsuchimikado": "masculino",
  "Komoe": "feminino",
  "Yomikawa": "feminino",
  "Index": "feminino",
  "Nakimoto": "masculino",
  "Secretary": "feminino",
  "Kaori": "feminino",
  "Styl": "masculino",
  "Himegami": "feminino",
  "Izzard": "masculino",
  "Mikoto": "feminino",
  "Kuroko": "feminino",
  "Saten": "feminino",
  "Uiharu": "feminino",
  "Harumi": "feminino",
  "Mii": "feminino",
  "Wataru": "masculino",
  "Hebitani": "masculino",
  "Tamezo": "masculino",
  "Miho": "feminino",
  "Erii": "feminino",
  "Telestina": "feminino",
  "Mitsuko": "feminino",
  "Maaya": "feminino",
  "Wannai": "feminino",
  "Mugino": "feminino",
  "Frenda": "feminino",
  "Riko": "feminino",
  "Saiai": "feminino",
  "Maika": "feminino",
  "Hanano": "feminino",
  "Misaka10031": "feminino",
  "Accelerator": "masculino",
  "Shinobu": "feminino",
  "Febrie": "feminino",
  "Janie": "feminino",
  "Haruki": "masculino",
  "Kosako": "masculino",
  "Hirotada": "masculino",
  "Kenji": "masculino",
  "Sakurai": "feminino",
  "Shiratori": "feminino",
  "Gabriel": "",
  "Ouma": "masculino",
  "Mitsuki": "masculino",
  "Unabara": "feminino",
  "LastOrder": "feminino",
  "Yoshikawa": "feminino",
  "Hyouka": "feminino",
  "Sherry": "feminino",
  "Orsola": "feminino",
  "Agnese": "feminino",
  "Lucia": "feminino",
  "Angeline": "feminino",
  "Ringo": "feminino",
  "Kakine": "masculino",
  "Kaibi": "feminino",
  "Yobou": "masculino",
  "Souji": "masculino",
  "Esther": "feminino",
  "Huotou": "feminino",
  "Iizumi": "feminino",
  "Naruha": "feminino",
  "Yakumaru": "feminino",
  "Seike": "masculino",
  "Hirumi": "feminino",
  "Hishigata": "masculino",
  "Himegi": "feminino",
  "Yumi": "feminino",
  "Mami": "feminino",
  "Chef": "masculino",
  "Tao": "masculino",
  "Musujime": "feminino",
  "Fukiyose": "feminino",
  "Oriana": "feminino",
  "Lidvia": "feminino",
  "Professor": "masculino",
  "Yoshio": "masculino",
  "Xochtl": "feminino",
  "Saraku": "masculino",
  "Misaki": "feminino",
  "Junko": "feminino",
  "Mitori": "feminino",
  "Dolly": "feminino",
  "Megumi": "feminino",
  "Satori": "feminino",
  "Mei": "feminino",
  "Kii": "feminino",
  "Kisa": "feminino",
  "Kazan": "feminino",
  "Wakana": "feminino",
  "Fuigo": "feminino",
  "Gensei": "masculino",
  "Sogiita": "masculino",
  "Itsuwa": "feminino",
  "Biagio": "masculino",
  "Vento": "feminino",
  "Terra": "masculino",
  "Acqua": "masculino",
  "Flamma": "masculino",
  "Amata": "masculino",
  "Rakko": "feminino",
  "Iruka": "feminino",
  "Makigami": "feminino",
  "Kuriba": "feminino",
  "Doppelganger": "feminino",
  "Ayame": "feminino",
  "Shuri": "feminino",
  "Asai": "masculino",
  "Sakata": "feminino",
  "Yasu": "feminino",
  "Shoubu": "masculino",
  "Tsurigane": "feminino",
  "Raifu": "feminino",
  "Suzuran": "feminino",
  "Kimi": "feminino",
  "Honoka": "feminino",
  "Kuruwa": "feminino",
  "Hamazura": "masculino",
  "Ritoku": "masculino",
  "Hanzou": "masculino",
  "Sunazara": "masculino",
  "Monaka": "feminino",
  "Elizard": "feminino",
  "Villian": "feminino",
  "Rimea": "feminino",
  "Carissa": "feminino",
  "KnightLeader": "masculino",
  "Beiloupe": "feminino",
  "Floris": "feminino",
  "Lessar": "feminino",
  "Lancis": "feminino",
  "Flamma": "masculino",
  "Shiokishi": "masculino",
  "Thomas": "masculino",
  "Stephanie": "feminino",
  "Aiwass": "",
  "Elizalina": "feminino",
  "Sasha": "feminino",
  "Fremea": "feminino",
  "Hisato": "feminino"
};

const arcList = [
  "Index Arc", "Deep Blood Arc", "Sisters Arc (Index)", "Angel Falldown Arc",
  "Kazakiri Hyouka Arc", "Three Stories Arc", "Orsola Acquinas Rescue Arc",
  "Tree Diagram Remnant Arc", "Daihasei Festival Arc (Index)", "La Regina Del Mar Adriatico Arc",
  "Academic City Invasion Arc", "Skill Out Uprising Arc", "Battle Royale Arc",
  "Document of Constantine Arc", "Acqua of the back Arc", "Royal British Family Arc",
  "DRAGON Arc", "World War III Arc", "Freshmen Arc", "Homecoming Arc", "Hawaii Invasion Arc",
  "Baggage City Arc", "Ichinaran Festival Arc", "Agitate Halation Arc", "Magic God Othinus Arc",
  "Mental Out Arc", "St. Germain Arc", "Magic God Invasion Arc", "World Rejecter Arc",
  "Salome Arc", "Element Arc", "Kamisato Rescue Arc", "Aleister Crowley Arc", "Processor Suit Arc",
  "Coronzon Arc", "Kamijou Arc", "Christmas Eve Arc", "Christmas Day Arc", "Operation Handcuffs Arc",
  "Los Angeles Arc", "Post Handcuffs Arc", "New Year's Eve Arc", "Hell Tour Arc", "Ressurection Arc",
  "Level Upper Arc", "Big Spider Arc", "Poltergeist Arc", "Sisters Arc (Railgun)", "Silent Party Arc",
  "Daihasei Festival Arc (Railgun)", "Dream Ranker Arc", "Jailbreaker Arc", "First Year Arc",
  "Necromancer Arc", "Nectar Arc", "Enemy ITEM Arc", "Honey Bee Queen Arc", "Dark Justice Arc",
  "Mugino Family Arc", "Yuzuriha Ringo Arc", "Astral Buddy Arc", "Tokiwadai Election Arc"
];

window.personagens = personagens;
window.arcList = arcList;